export interface WebsiteContentField {
  key: string;
  section:
    "hero" | "services" | "process" | "work" | "about" | "finalCta" | "footer";
  label: string;
  multiline: boolean;
  valueEn: string;
  valueAr: string;
}

/**
 * Seed/default copy for the public one-page site, matching ATOI Studio.html
 * (the authoritative design reference). Also doubles as the fallback used
 * if a key is ever missing from the database.
 */
export const DEFAULT_WEBSITE_CONTENT: WebsiteContentField[] = [
  {
    key: "hero.eyebrow",
    section: "hero",
    label: "Eyebrow",
    multiline: false,
    valueEn: "Bahrain-based software studio",
    valueAr: "استوديو برمجيات من البحرين",
  },
  {
    key: "hero.heading",
    section: "hero",
    label: "Heading",
    multiline: false,
    valueEn: "Give us the problem. We ship the software.",
    valueAr: "أعطنا المشكلة. سنشحن لك البرمجيات.",
  },
  {
    key: "hero.body",
    section: "hero",
    label: "Body",
    multiline: true,
    valueEn:
      "We design and build websites, web applications and internal software for businesses in Bahrain and beyond.",
    valueAr:
      "نصمم ونبني مواقع إلكترونية وتطبيقات ويب وبرمجيات داخلية للشركات في البحرين وخارجها.",
  },
  {
    key: "hero.ctaPrimary",
    section: "hero",
    label: "Primary button label",
    multiline: false,
    valueEn: "Start a project",
    valueAr: "ابدأ مشروعاً",
  },
  {
    key: "hero.ctaSecondary",
    section: "hero",
    label: "Secondary button label",
    multiline: false,
    valueEn: "See our work",
    valueAr: "شاهد أعمالنا",
  },
  {
    key: "services.heading",
    section: "services",
    label: "Heading",
    multiline: false,
    valueEn: "Six things, done properly.",
    valueAr: "ستة أشياء، بإتقان.",
  },
  {
    key: "services.item1.name",
    section: "services",
    label: "Service 1 name",
    multiline: false,
    valueEn: "websites",
    valueAr: "مواقع إلكترونية",
  },
  {
    key: "services.item1.description",
    section: "services",
    label: "Service 1 description",
    multiline: true,
    valueEn: "Fast, clear, and editable by your team.",
    valueAr: "سريعة وواضحة وقابلة للتعديل من فريقك.",
  },
  {
    key: "services.item1.duration",
    section: "services",
    label: "Service 1 duration",
    multiline: false,
    valueEn: "3–6 wks",
    valueAr: "٣-٦ أسابيع",
  },
  {
    key: "services.item2.name",
    section: "services",
    label: "Service 2 name",
    multiline: false,
    valueEn: "web applications",
    valueAr: "تطبيقات ويب",
  },
  {
    key: "services.item2.description",
    section: "services",
    label: "Service 2 description",
    multiline: true,
    valueEn: "Accounts, permissions and screens built for daily use.",
    valueAr: "حسابات وصلاحيات وشاشات مبنية للاستخدام اليومي.",
  },
  {
    key: "services.item2.duration",
    section: "services",
    label: "Service 2 duration",
    multiline: false,
    valueEn: "6–14 wks",
    valueAr: "٦-١٤ أسبوعاً",
  },
  {
    key: "services.item3.name",
    section: "services",
    label: "Service 3 name",
    multiline: false,
    valueEn: "saas products",
    valueAr: "منتجات ساس",
  },
  {
    key: "services.item3.description",
    section: "services",
    label: "Service 3 description",
    multiline: true,
    valueEn: "Idea to paid product, then releases after launch.",
    valueAr: "من الفكرة إلى منتج مدفوع، ثم تحديثات بعد الإطلاق.",
  },
  {
    key: "services.item3.duration",
    section: "services",
    label: "Service 3 duration",
    multiline: false,
    valueEn: "ongoing",
    valueAr: "مستمر",
  },
  {
    key: "services.item4.name",
    section: "services",
    label: "Service 4 name",
    multiline: false,
    valueEn: "internal tools",
    valueAr: "أدوات داخلية",
  },
  {
    key: "services.item4.description",
    section: "services",
    label: "Service 4 description",
    multiline: true,
    valueEn: "The spreadsheet that runs your operation, rebuilt properly.",
    valueAr: "جدول البيانات الذي يدير عملك، معاد بناؤه بشكل صحيح.",
  },
  {
    key: "services.item4.duration",
    section: "services",
    label: "Service 4 duration",
    multiline: false,
    valueEn: "4–10 wks",
    valueAr: "٤-١٠ أسابيع",
  },
  {
    key: "services.item5.name",
    section: "services",
    label: "Service 5 name",
    multiline: false,
    valueEn: "automation",
    valueAr: "الأتمتة",
  },
  {
    key: "services.item5.description",
    section: "services",
    label: "Service 5 description",
    multiline: true,
    valueEn: "Systems that talk to each other; reports that write themselves.",
    valueAr: "أنظمة تتواصل مع بعضها؛ تقارير تكتب نفسها.",
  },
  {
    key: "services.item5.duration",
    section: "services",
    label: "Service 5 duration",
    multiline: false,
    valueEn: "2–5 wks",
    valueAr: "٢-٥ أسابيع",
  },
  {
    key: "services.item6.name",
    section: "services",
    label: "Service 6 name",
    multiline: false,
    valueEn: "custom software",
    valueAr: "برمجيات مخصصة",
  },
  {
    key: "services.item6.description",
    section: "services",
    label: "Service 6 description",
    multiline: true,
    valueEn: "The thing no product on the market does.",
    valueAr: "الشيء الذي لا يقدمه أي منتج في السوق.",
  },
  {
    key: "services.item6.duration",
    section: "services",
    label: "Service 6 duration",
    multiline: false,
    valueEn: "by scope",
    valueAr: "حسب النطاق",
  },
  {
    key: "process.heading",
    section: "process",
    label: "Heading",
    multiline: false,
    valueEn: "From idea to production.",
    valueAr: "من الفكرة إلى الإنتاج.",
  },
  {
    key: "process.step1.name",
    section: "process",
    label: "Step 1 name",
    multiline: false,
    valueEn: "Tell us what you need",
    valueAr: "أخبرنا بما تحتاجه",
  },
  {
    key: "process.step1.description",
    section: "process",
    label: "Step 1 description",
    multiline: true,
    valueEn: "We define the scope, priorities, and technical approach with you.",
    valueAr: "نحدد النطاق والأولويات والنهج التقني معك.",
  },
  {
    key: "process.step2.name",
    section: "process",
    label: "Step 2 name",
    multiline: false,
    valueEn: "See progress every week",
    valueAr: "شاهد التقدم كل أسبوع",
  },
  {
    key: "process.step2.description",
    section: "process",
    label: "Step 2 description",
    multiline: true,
    valueEn: "You get working builds on a real URL, not just status updates.",
    valueAr: "تحصل على إصدارات عمل على رابط حقيقي، وليس مجرد تحديثات حالة.",
  },
  {
    key: "process.step3.name",
    section: "process",
    label: "Step 3 name",
    multiline: false,
    valueEn: "Own what we build",
    valueAr: "امتلك ما نبنيه",
  },
  {
    key: "process.step3.description",
    section: "process",
    label: "Step 3 description",
    multiline: true,
    valueEn: "Clean code, documentation, and a project your team can continue developing.",
    valueAr: "كود نظيف وتوثيق ومشروع يستطيع فريقك مواصلة تطويره.",
  },
  {
    key: "work.heading",
    section: "work",
    label: "Heading",
    multiline: false,
    valueEn: "Selected Work",
    valueAr: "أعمال مختارة",
  },
  {
    key: "work.intro",
    section: "work",
    label: "Supporting copy",
    multiline: true,
    valueEn:
      "Real projects. Real impact. Built with modern technology for forward-thinking businesses.",
    valueAr:
      "مشاريع حقيقية وتأثير حقيقي. نبني بتقنيات حديثة للشركات ذات النظرة المستقبلية.",
  },
  {
    key: "work.seeAllLabel",
    section: "work",
    label: '"See all projects" label',
    multiline: false,
    valueEn: "See all projects",
    valueAr: "عرض كل المشاريع",
  },
  {
    key: "finalCta.eyebrow",
    section: "finalCta",
    label: "Eyebrow",
    multiline: false,
    valueEn: "start a project",
    valueAr: "ابدأ مشروعاً",
  },
  {
    key: "finalCta.heading",
    section: "finalCta",
    label: "Heading",
    multiline: false,
    valueEn: "Have something worth building?",
    valueAr: "هل لديك ما يستحق البناء؟",
  },
  {
    key: "finalCta.body",
    section: "finalCta",
    label: "Body",
    multiline: true,
    valueEn: "Two minutes in the form. We reply within two working days.",
    valueAr: "دقيقتان في النموذج. سنرد خلال يومي عمل.",
  },
  {
    key: "finalCta.ctaLabel",
    section: "finalCta",
    label: "Button label",
    multiline: false,
    valueEn: "Open the inquiry form",
    valueAr: "افتح نموذج الاستفسار",
  },
  {
    key: "footer.tagline",
    section: "footer",
    label: "Company tagline",
    multiline: false,
    valueEn: "Software solutions, made straightforward.",
    valueAr: "حلول برمجية، بأسلوب مباشر.",
  },
];

export const DEFAULT_WEBSITE_CONTENT_MAP: Record<
  string,
  { valueEn: string; valueAr: string }
> = Object.fromEntries(
  DEFAULT_WEBSITE_CONTENT.map((f) => [
    f.key,
    { valueEn: f.valueEn, valueAr: f.valueAr },
  ]),
);
